### ISSUE TITLE
please update bower to get v1.0

### ISSUE THREAD

**Issue by ChristianSchramm** [robflaherty/jquery-scrolldepth#103]
Hey there,

when i use bower install for scroll-depth i only get the v0.9.1 instead of v1.0.

best regards

**Comment by robflaherty** [comment]
Thanks. It may be because I tagged the latest version as "1.0" instead of "1.0.0". I updated the tag name. Let's see if that fixes it.

**Comment by robflaherty** [comment]
Yep, that fixed it. Thanks for the heads-up!
