### ISSUE TITLE
Specify page we track

### ISSUE THREAD

**Issue by sheepsy90** [robflaherty/jquery-scrolldepth#104]
Hey,

I wonder if it it possible to have a custom dimension or something which can be specified on init, that can be used to track the page in union with the scrolling (to differ blog articles)

Is that possible?

**Comment by robflaherty** [comment]
Hi,
The page associated with an event is automatically tracked in GA. In the Events section of GA there's a Pages screen that groups the events by pages.

You can also access the page data by going to the event you want and then setting Page as the Secondary Dimension.

**Comment by sheepsy90** [comment]
Sorry, I did not know this - but found the setting now :)
