### ISSUE TITLE
 Integrate with Google Tag Manager

### ISSUE THREAD

**Issue by taniabarreira** [robflaherty/jquery-scrolldepth#105]
Very usefull post about integrate with Google Tag Manager:
https://www.advancedwebranking.com/blog/how-to-track-scroll-depth-with-google-tag-manager/

and video
https://www.youtube.com/watch?v=UoOh58pvqG4

**Comment by taniabarreira** [comment]
and video `<iframe width="560" height="315" src="https://www.youtube.com/embed/UoOh58pvqG4" frameborder="0" allowfullscreen></iframe>`

**Comment by bmd** [comment]
This library already works with GTM by allowing you to specify whether events get pushed to the dataLayer or tracked via GA directly. What's the issue here?

**Comment by taniabarreira** [comment]
None bmd, just a tip!
Thank you
