### ISSUE TITLE
Correct way to separate the scrolling trackers on different pages

### ISSUE THREAD

**Issue by Anon-Penguin** [robflaherty/jquery-scrolldepth#106]
What's the "correct" way to separate scrolling depth trackers on different pages? So far I've just manually edited the library to change the Event Category/Event Action string constant, but IDK if there's a better way that I'm missing.

**Comment by mef** [comment]
The most simple way would be to use the `Behavior > Events > Pages` report in Google Analytics. This lets you select pages, and see their scroll depth metrics.

No need to modify the plugin's code this way ;)

![screenshot - 010817 - 11 24 09](https://user-images.githubusercontent.com/925443/28818655-04da25ae-76ac-11e7-94ca-42feb266c7e7.png)


Another way is to go to `Behavior > Events > Top events`, then click on "Scroll Depth", then "Percentage", then add "Page" as a secondary dimension. This gives you all pages metrics in one table.
