### ISSUE TITLE
Latest Version with GTM - No dataLayer pushes

### ISSUE THREAD

**Issue by RottenJoe** [robflaherty/jquery-scrolldepth#108]
Hi,

I've decided to update the plug-in as I was still running the 2014 v0.4.1. 

Using GTM, for now, I just implemented the custom HTML tag, with the trigger firing on DOM ready. Theoretically, the script should already fire the dataLayer event 'ScrollDistance', am I correct?

Guide used to set up with GTM (although it was already set up with the older version): http://www.amazeemetrics.com/en/blog/google-tag-manager-tutorial-scroll-tracking-5-steps

Please see my testing site: http://lazycheapworkout.com/

Unfortunately the latest version (v1.0) does not fire any dataLayer pushes at all. I've set up both versions simultaneously; the old version pushes the event 'ScrollDistance_Old', while the new one should push the standard 'ScrollDistance'.

Im aware of the jQuery error, but I figured that the old version also used $-jQuery and therefore the new one should also not be broken because of this. 

Thanks a lot for your help in advance!

PS: If you need any more information, please let me know!

**Comment by robflaherty** [comment]
Sorry, I don't see the plugin installed on your test site.

**Comment by RottenJoe** [comment]
Hi, thanks for you quick response!

Well I deployed it through GTM as in the above guide. I use a custom HTML tag with the code from _jquery.scrolldepth.js_ which fires on DOM ready. Therefore you won't find anything in the source code indicating that the plug-in is present. 

Do I need to load any other JS script before triggering my GTM tag with the actual script?

Thanks!

![image](https://cloud.githubusercontent.com/assets/25005673/24364450/19b345f2-1313-11e7-84fa-9158f693fef3.png)


![image](https://cloud.githubusercontent.com/assets/25005673/24364442/13313770-1313-11e7-950e-6b0bd23205f5.png)

**Comment by robflaherty** [comment]
I think there's an error in your GTM configuration and the plugin isn't being loaded. If you inspect the jQuery object you should see the scrollDepth() method but it's returning `undefined`.

**Comment by RottenJoe** [comment]
Okay, this sounds a bit strange to me. I guess you're talking about the method defined on line 53:

`$.scrollDepth = function(options) {`

The thing is, that also the old version uses this method (line 25) and this one works perfectly.

Is there anything else you know of that is needed to run this plug-in via GTM?

Thanks for your time!

**Comment by robflaherty** [comment]
Sorry, I forgot I had an ad blocker on when I looked at your test site and it was blocking the GTM script.

I think you just need to resolve the JS error. Try replacing the `$` alias with `jQuery` in these statements related to newsletter stuff

![screen shot 2017-03-30 at 10 09 07 am](https://cloud.githubusercontent.com/assets/159644/24508440/64ba0138-1531-11e7-8150-2ccfb99bf9e4.png)

**Comment by RottenJoe** [comment]
Hi again!

I've removed the newsletter stuff, which was a completely different tag I had deployed in a previous test. Moreover I replaced all `$` alias with `jQuery`. Now the console does not show any JS errors:

![image](https://cloud.githubusercontent.com/assets/25005673/24539170/8272522c-15ed-11e7-98c5-4f4a0cec21f5.png)

Unfortunately, the script does still not execute correctly. Do you know of people deploying v1.0 with GTM and it worked? Maybe it's just some additional thing that needs to be taken care of before loading through GTM that I'm missing.

Thanks again!

**Comment by RottenJoe** [comment]
Hi again!

This is now a bit embarrassing, but I've figured out why it didn't load correctly. As the older version called the method itself, I assumed that the newer does as well. But if I just had a quick look at the code I should have known... :( Incredibly my bad..! Thanks for your support tho.
