### ISSUE TITLE
Surprisingly low number of events

### ISSUE THREAD

**Issue by bennybee** [robflaherty/jquery-scrolldepth#112]
Have added the plugin to all pages, the only option I have set is userTiming: false. All the pages on the site are very long.

When I console out the eventHandler I see data on all pages.

But I am getting very low results in Analytics. For example a day will have over 1000 page views but only 4 'Percentage' events fired. I'm certain that there should be a lot more. 

I use the 'Event Tracking Tracker' Chrome Extension and all my click events show up in there but none of the scroll events.

Is there any way I can debug the issue further? Anything that would stop the events firing in some instances?

Thanks

**Comment by arkid** [comment]
I have the same problem.  For the last 7 days of statistics I have 153 events listed in total but there were 1,858 users/ 2233 sessions over that time period on the website.   

What could explain this ?

**Comment by robflaherty** [comment]
URL?

**Comment by arkid** [comment]
> URL?
https://www.anderson-sheppard.co.uk/bespoke/

**Comment by robflaherty** [comment]
@arkid if you paste your initialization code into the console you'll see the events firing as expected. this suggests the problem is a race condition where the Scroll Depth initialization code is running before GA has been initialized. i'd also try removing the "trackerName:'gtag_UA_5803553_1'" option. this option is only needed if you're tracking multiple GA profiles on the same page.

**Comment by arkid** [comment]
Thanks @robflaherty , have you seen race conditions like this before being an issue with your plugin?    You think putting that extra code inside a window.load instead of document.ready is a good idea ?

**Comment by robflaherty** [comment]
Waiting for window.load shouldn't be necessary but you can try it. It shouldn't affect the plugin.

I would first try removing the trackerName option and removing this empty "name" parameter from the gtag config (unless it's intentional):

gtag('config', 'UA-5803553-1', {'name':''});
