### ISSUE TITLE
Custom names for event category, action, label

### ISSUE THREAD

**Issue by vasyl-shumskyi** [robflaherty/jquery-scrolldepth#115]
Thanks for the awesome plugin.

Is it possible to setup _custom_ names for event category, action, label?

For example, my events organized in the following manner: 

```javascript
event_category:  'scrolling'
event_action: 'scrolled 25%' // 50%, 75%, 100% 
event_label:  'page title'
```

Thanks!

**Comment by robflaherty** [comment]
No plans to add this as a feature so you'd have to hard code the desired names in the plugin :)
