### ISSUE TITLE
Any common issues that would stop any events registering in GA ?

### ISSUE THREAD

**Issue by arkid** [robflaherty/jquery-scrolldepth#116]
I set this up yesterday on a [site](https://www.anderson-sheppard.co.uk) that is definitely getting visitors so I was expecting to see something today but there are zero events inside of Google Analytics.

For ref, any kind of list of common issues you could list on the github page/separate website would be great.

Thanks for any ideas!

**Comment by googleanalyticsresoneo** [comment]
Hi

First place for Diagnostics: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

Open your console and browse your site, look at error messages.

Here you get for example
Running command: ga("send", "event", "YTPlayer", "play", "Sb-bSUbqm28")
Command ignored. Unknown target: undefined

To solve this, go to GTM and tick "Tracker Name" but left it blank
https://www.simoahava.com/gtm-tips/be-careful-with-the-tracker-name-setting/

**Comment by googleanalyticsresoneo** [comment]
Hum, sorry, looks like new stuff coming in gtag.js ..
You could try using
gtag('config', 'UA-5803553-1', {'name':undefined});
Or
gtag('config', 'UA-5803553-1', {'name':''});
as a workaround

**Comment by arkid** [comment]
I've modified the gtag line now.    I still see "No tags fired for event: ScrollDistance" etc.  To clarify, do I need to do anything in GTM?  I haven't ever used this for this particular account/domain.

**Comment by googleanalyticsresoneo** [comment]
looks like you have some cache in place as the source code is unchanged 
the goal is to remove the name option here in the console log
ga("create", "UA-5803553-1", {cookieDomain: "auto", name: "gtag_UA_5803553_1"})

no you don't need GTM, I was abused by gtag that mimics GTM by some aspects

**Comment by googleanalyticsresoneo** [comment]
doesn't seem to work on my side either.
is there a trackerName option in this  project ??
set the value to 'gtag_UA_5803553_1'

**Comment by arkid** [comment]
So there is a cache plugin on the site but when i viewed the source I saw gtag('config', 'UA-5803553-1', {'name':''});    Anyhow, I've cleared the cache so you should be able to see it too.

I dont know if there is a trackerName... how do I check/set that ?

**Comment by googleanalyticsresoneo** [comment]
According to https://scrolldepth.parsnip.io 
you have that option

`jQuery.scrollDepth({minHeight: 800,userTiming: false,trackerName:'gtag_UA_5803553_1'});
`
You may also try 
`jQuery.scrollDepth({minHeight: 800,userTiming: false,trackerName:'gtag_UA_5803553_1',gtmOverride:true});`

**Comment by arkid** [comment]
Thanks for your help so far.  So I've made these changes you recommended including gtmOverrride parameter and all the error debug has gone when pages are interacted with.  However there are simply no events at all showing up in the related analytics account !? What could the cause of that be ?
