### ISSUE TITLE
Current minified version doesn't work

### ISSUE THREAD

**Issue by mherrmann** [robflaherty/jquery-scrolldepth#119]
Thank you for taking the time to open source and maintain a very useful plugin. I just started using it on https://build-system.fman.io/. One thing I noticed there is that no events are sent when I use `jquery.scrolldepth.min.js`. If I change to `jquery.scrolldepth.js`, everything runs smoothly. I'm using jQuery 3.3.1 and the following code:

```
<script type="text/javascript">
    jQuery(function() {
      jQuery.scrollDepth();
    });
</script>
```

**Comment by vladislavqq** [comment]
Can confirm, min file doesn't work. If nothing appears under Events section in Google Analytics try to switch to normal version, or simply, minify it

**Comment by robflaherty** [comment]
Sorry for delayed response. I wasn't able to reproduce but I regenerated the minified version with the latest release and hope that fixes it.
