### ISSUE TITLE
ScrollTiming event doesn't use nonInteraction variable

### ISSUE THREAD

**Issue by dmatthew** [robflaherty/jquery-scrolldepth#120]
The **_ScrollTiming_** event doesn't use the nonInteraction option, so all of the ScrollTiming events are considered interactive.

**Comment by robflaherty** [comment]
Unless they've recently changed things user timing events don't support the non-interaction option. They should be non-interactive no matter what :)

**Comment by dmatthew** [comment]
Thanks for the quick feedback. I just found the issue is with the Drupal Scroll Depth Analytics module. It uses a custom eventHandler to send its own Google Analytics events, skipping over this module's use of nonInteraction.
