### ISSUE TITLE
The non-jQuery version seems unable to track in gtag.js

### ISSUE THREAD

**Issue by jonathanstegall** [robflaherty/jquery-scrolldepth#124]
Recently I was working on an Analytics install that uses scroll-depth events. I needed to convert it from analytics.js to gtag.js in preparation for an upgrade to Analytics version 4, which can use gtag.js.

I noticed that the non-jQuery version, which I guess is maintained by @leighmcculloch, does not work with gtag.js because it's missing the changes from versions 1.1 and 1.2.

I'm curious if there are any plans to get these changes into the non-jQuery version (I noticed that the fork doesn't allow issues).

**Comment by leighmcculloch** [comment]
Not sure how difficult it will be to track upstream at this point, but we can try. https://github.com/leighmcculloch/gascrolldepth.js/pull/5

**Comment by leighmcculloch** [comment]
Looks pretty substantial, so I'm archiving the non-jQuery version. It is unmaintained.
