### ISSUE TITLE
Add option to define a bottom element.

### ISSUE THREAD

**Issue by LaptopHeaven** [robflaherty/jquery-scrolldepth#31]
Some of our page lengths vary due to comments.
It would be nice to be able to define the end of the actual content on the page.

       var defaults = {
           minHeight: 0,
           elements: [],
           percentage: true,
           userTiming: true,
           pixelDepth: true,
           bottomElement: ''
       };
...
      
    var docHeight = $(document).height(),
        winHeight = window.innerHeight ? window.innerHeight : $window.height(),
        scrollDistance = $window.scrollTop() + winHeight;

			if (options.bottomElement) {
				docHeight = $(options.bottomElement).offset().top;
      }
  		// Recalculate percentage marks
      var marks = calculateMarks(docHeight),

Then pass the option through:

    $(function() {
        $.scrollDepth({bottomElement:'#bottomElement'});
    });

**Comment by markadrake** [comment]
Thanks @LaptopHeaven this worked for something I was trying to pull off.
