### ISSUE TITLE
Add support for piwik

### ISSUE THREAD

**Issue by lazysoundsystem** [robflaherty/jquery-scrolldepth#47]
As this is already handling classic and universal analytics, it seems straightforward to let it handle piwik tracking as well.

I've created a pull request for this if you think it's not out of scope. [#46](https://github.com/robflaherty/jquery-scrolldepth/pull/46)

**Comment by tholu** [comment]
+1

**Comment by alextjtaylor** [comment]
where do we stand with supporting Piwik at the moment? I would love to use this script

**Comment by robflaherty** [comment]
@alextjtaylor check out the `eventHandler` option. that turns off the GA events and passes the scroll data to a callback that you can use to send events to Piwik or any other service.
