### ISSUE TITLE
Option to specify a container other than the window

### ISSUE THREAD

**Issue by adamtlord** [robflaherty/jquery-scrolldepth#57]
My layout is using a fixed sidebar that requires the main content to be inside a scrolling div, so scroll events bound to the window never fire. What would you think about adding an option to specify the container that actually does the scrolling?

**Comment by robflaherty** [comment]
Thanks for the feedback. I need to think about this one a little more.

**Comment by grzesiekp1308** [comment]
In my opinion scroll percentage tracking for DOM elements will be excellent feauture.

**Comment by robflaherty** [comment]
Agreed. Planning to add this in the next update. Thanks for the feedback.
