### ISSUE TITLE
GTM: Allow user to specify his own dataLayer object and field names

### ISSUE THREAD

**Issue by yuhui** [robflaherty/jquery-scrolldepth#58]
GTM allows the dataLayer to be renamed to something else, to prevent conflicts with existing "dataLayer" objects.

Also, users might want to specify their own event and field names, instead of using the hard-coded ones in this plug-in.

(I've already created a branch for all of the above in my local repository and using it in some production instances, but can't push my branch to remote.)

**Comment by robflaherty** [comment]
>GTM allows the dataLayer to be renamed to something else, to prevent conflicts with existing "dataLayer" objects.

I agree, this should be an option. I'm planning to add it along with an option to specify the GA global variable.

>Also, users might want to specify their own event and field names, instead of using the hard-coded ones in this plug-in.

Do you mean changing the event category, action, and labels? I know some users might want to customize those but it's not a feature I'm planning to support yet.

**Comment by robflaherty** [comment]
Fixed
