### ISSUE TITLE
Weird eventlabels being recorded

### ISSUE THREAD

**Issue by nowton** [robflaherty/jquery-scrolldepth#59]
We have succesfully implemented this on a page, but see a couple of weird numeric labeled events in our reports; for instance: 3250, 3000, 11750 and 6250. Any ideas what might be causing this? Thanks in advance.

**Comment by robflaherty** [comment]
These are the Pixel Depth events
> Pixel Depth events record the scroll distance in pixels, rounded down to the nearest 250px increment. While the percentage events provide a relative measure of scroll depth, pixel depth events provide an absolute measure. This can be useful for comparing across devices where the relative percentage heights vary greatly (e.g., desktop vs mobile).

You can turn them off using the `pixelDepth` option.

**Comment by nowton** [comment]
Thanks!
