### ISSUE TITLE
GTM: to use this feature visit: EVENT-TRACKING.COM

### ISSUE THREAD

**Issue by patriksima** [robflaherty/jquery-scrolldepth#60]
Hello,

in GA shows only "to use this feature visit: EVENT-TRACKING.COM"

Where I did a mistake?

Thank you

**Comment by robflaherty** [comment]
Hi,

I think there's another script on your site causing this. Do you have a URL I could look at?

Thanks

**Comment by patriksima** [comment]
Hello,

https://wrongware.cz (There is only one javascript file which not contains these words.)

can be a problem in ssl?

**Comment by robflaherty** [comment]
I've seen a few reports of this on twitter and the GA forums. It's not related to the Scroll Depth plugin. Some other source is injecting spam events into GA. Some more info here:

https://productforums.google.com/forum/#!searchin/analytics/to$20use$20this$20feature$20visit$3A$20EVENT-TRACKING.COM/analytics/jYJ_1lYpIRE/InFSU6yCl8oJ

**Comment by patriksima** [comment]
Ok, thank you.
