### ISSUE TITLE
Master slider conflict 

### ISSUE THREAD

**Issue by lisestrandlien** [robflaherty/jquery-scrolldepth#63]
When installing WP-scroll Depth, the plugin "Master Slider" will not load: http://codecanyon.net/item/master-slider-wordpress-responsive-touch-slider/7467925

**Comment by robflaherty** [comment]
Hey,
WP Scroll Depth is a different project, maintained by other developers. I suggest getting in touch with them (link below) or contacting the Master Slider developers.

https://wordpress.org/support/plugin/wp-scroll-depth

**Comment by lisestrandlien** [comment]
Ok, I have used the script at this site: http://scrolldepth.parsnip.io/,
not the plugin.


2015-06-08 20:56 GMT+02:00 Rob Flaherty <notifications@github.com>:

> Closed #63 <https://github.com/robflaherty/jquery-scrolldepth/issues/63>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robflaherty/jquery-scrolldepth/issues/63#event-325592012>
> .
>



-- 
------------------------------------------
Lise Strandlien
Tlf. 92458021
http://www.strandlien.com
--------------------------------

**Comment by robflaherty** [comment]
Sorry, "WP Scroll Depth" is a wordpress plugin so I got confused.

Do you have a URL I can look at?
