### ISSUE TITLE
It push only the baseline and not the 25, 50,75 and 100%

### ISSUE THREAD

**Issue by khha** [robflaherty/jquery-scrolldepth#64]
I am using your script to monitor the scroll behavior of the visitors. It is a great script. I installed to our SharePoint 2013 site. I load first the track code (InPage Analyse is enabled in the track code). After the track code I do the registration of your js file. As last but not least I run the function "scrollDepth" after the page is loaded. Something like this:

<head>
here is my track code..
<script type="text/javascript" src="/_layouts/15/BrabantWater.Internet/js/jquery.scrolldepth.js"></script>
<script>
            $(window).bind("load", function () {
                jQuery(function () {
                    jQuery.scrollDepth();
                });
            });
 </script>
</head>

When I scroll and go to GA I see only the baseline is pushed. When I debug I see it go to my breakpoints after each scroll move. What can I do to find the issue ?

**Comment by robflaherty** [comment]
URL?

**Comment by khha** [comment]
It is a site on my development machine. When I turn on the chrome dev bar and show the console you can see it is sending as last the baseline.See printscreen:

http://s23.postimg.org/azkg7kzrf/Naamloos.png

**Comment by robflaherty** [comment]
Sorry but there's not enough information here for me to determine the error. I don't think it's caused by the plug-in. There may be an error on the page happening after the baseline event fires, preventing the other events from sending.

**Comment by khha** [comment]
Here is more information:

I have 3 js files registered in the header in this order:
 
<script type="text/javascript" src="/_layouts/15/MyCompanyName/js/Libraries/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/_layouts/15/MyCompanyName/js/Libraries/jquery.scrolldepth.min.js"></script>
<script type="text/javascript" src="/_layouts/15/MyCompanyName/js/custom.js?v=1.3"></script>

In "jquery.scrolldepth.min.js" there is a function named "scrollDepth()". This function is using jQuery. In the custom.js I would like to start the function "scrollDepth()" which is declared in the js file "jquery.scrolldepth.min.js". I would like also to start this function after "jquery-1.9.1.min.js" and "jquery.scrolldepth.min.js" is loaded. Is this ok in my custom.js? I would like to avoid errors that the needed js files are not loaded.

jQuery(document).ready(function ($) {

    jQuery(function () {
        jQuery.scrollDepth();
    });

**Comment by khha** [comment]
I have some more information. The Baseline, 25, 50 and 75% is working in IE 10. In chrome 43.0.2357.124 m it is not working. When I debug in chrome it looks like he is comming inside my breakpoint of the throttle function. Inside the throttle function there is another function. It looks like he never comes inside that function. I am talking about this function:

return function () {
                alert("inline function");
                var now = new Date;
                if (!previous) previous = now;
                var remaining = wait - (now - previous);
                context = this;
                args = arguments;
                if (remaining <= 0) {
                    clearTimeout(timeout);
                    timeout = null;
                    previous = now;
                    result = func.apply(context, args);
                } else if (!timeout) {
                    timeout = setTimeout(later, remaining);
                }
                return result;
            };

**Comment by robflaherty** [comment]
Hi - I think there has to be some other code on the site causing a conflict. Or if you have the content inside an iframe or some other container, it's possible the window isn't actually scrolling. Without being able to view the site myself I don't think I can help resolve it :(
