### ISSUE TITLE
Track time when element gets into view and fire event after X seconds

### ISSUE THREAD

**Issue by Sanafan** [robflaherty/jquery-scrolldepth#65]
Hello Guys,
i installed your plugin and i wondered, if i'm the only person, who has a one page website because this feature is missing totaly. 

If a user of my website clicks on a link in the top navigation, the content scrolls down to the section he choosed. So now, if i have a page which looks like this: 

* Home
* Concept
* About
* Foo
* Bar

And the user chooses the content `Foo`, the page scrolls automatically through Home, Concept, and About and all three events for the view get triggerd and send to google. 

Why isn't there a counter which is configurable via the Admin Control-Panel in which i can define the time, the element has to be inside the view and after the time is over, the event gets triggerd?

That would help me a lot!

**Comment by robflaherty** [comment]
Thanks for the feedback. The plugin is meant to track scrolling but what you're describing is really jump navigation to anchor links. I'm not sure time-on-screen is the best way to infer real scrolling... maybe. It may make more sense for the plugin to be disabled for certain click events. Need to think about it some more.
