### ISSUE TITLE
No events firing after install

### ISSUE THREAD

**Issue by thowar2** [robflaherty/jquery-scrolldepth#66]
Having a strange issue where nothing is happening!

Executing `jQuery.scrollDepth();` in console returns `undefined`

Not sure what should be happening, so its difficult to debug.

URL: https://getartichoke.com/

**Comment by robflaherty** [comment]
Hey - it's because your GA implementation is using a custom tracker name "__gaTracker" instead of the default "ga". This problem is becoming more common so I'm working on a fix for it now. In the meantime you can edit the scroll depth script and replace the "ga" instances with "__gaTracker".

**Comment by robflaherty** [comment]
update: should have the fix out for this today

**Comment by robflaherty** [comment]
ok, fixed in version 0.8: https://github.com/robflaherty/jquery-scrolldepth/releases/tag/0.8.0

**Comment by thowar2** [comment]
Perfect! That is how Yoast's analytics plugin works so it makes sense to do that.

Also needed to disable GTM, though it would be nice to have it send to both!

Thanks a lot for the quick fix!
