### ISSUE TITLE
Events are not being tracked

### ISSUE THREAD

**Issue by laius** [robflaherty/jquery-scrolldepth#67]
I implemented the script by adding the code (after tracker initialization) to the Google Analyticator WordPress-Plugin (https://wordpress.org/plugins/google-analyticator/). Unfortunately, the script is not sending any events. Please help :-(.

![screenshot](https://cloud.githubusercontent.com/assets/10263587/8860025/42121886-3181-11e5-970e-d1ae8906cb89.png)

**Comment by robflaherty** [comment]
Hi, I need the URL of your site to be able to help you diagnosis the problem.

**Comment by laius** [comment]
Thx for the quick reply. URL is jobescape.net

**Comment by robflaherty** [comment]
Thanks. You're calling the Scroll Depth and Riveted functions correctly but I don't see the actual Scroll Depth and Riveted scripts loaded anywhere on the page.

![screen shot 2015-07-23 at 4 31 46 pm](https://cloud.githubusercontent.com/assets/159644/8861450/656ce730-3158-11e5-9701-7b6e46bdf548.png)

**Comment by laius** [comment]
OK - what do I need to do to load these scripts? What am I missing?

**Comment by robflaherty** [comment]
Just like any other scripts, you have to upload them to your server and then load them before calling them, like this:

```
<script src="jquery.scrolldepth.min.js"></script>
<script>
jQuery(function() {
  jQuery.scrollDepth();
});
</script>
```

**Comment by laius** [comment]
I guess I don't have enough code in my heart, so let me check back if I understood you correctly:

1) I need to place the function into a .js file and upload that into the .js folder of my wordpress theme folder.

2) I can then call the functions the same way I already am.

Am I correct?

**Comment by laius** [comment]
Hi there. I have been wrestling with this issue for the past few days and googled my a** off, but things are still not working. Is there a guide you can point me too. One for dummies with no particular coding experience?
