### ISSUE TITLE
Need a guide

### ISSUE THREAD

**Issue by laius** [robflaherty/jquery-scrolldepth#68]
Can't reopen the old issue (https://github.com/robflaherty/jquery-scrolldepth/issues/67), so I'm opening a new one:

I need a slightly more detailed guide on how to enable this script in wordpress. I spent several days trying to figure this out using google and haven't gotten any closer.

**Comment by robflaherty** [comment]
https://codex.wordpress.org/Using_Javascript
http://code.tutsplus.com/articles/how-to-include-javascript-and-css-in-your-wordpress-themes-and-plugins--wp-24321

Maybe try asking for help on the WordPress forums. Someone there may be able to help.
