### ISSUE TITLE
Non-jQuery version.

### ISSUE THREAD

**Issue by leighmcculloch** [robflaherty/jquery-scrolldepth#70]
I'd like to use this jQuery plugin on a website where jQuery won't be a dependency. It would be relatively simple to breakout the majority of the code and replace the jQuery calls with raw JavaScript, and then to still provide a jQuery version which wraps the core version.

I recently did this with [gaplaylength.js](https://github.com/leighmcculloch/gaplaylength.js) which was inspired by jquery-scrolldepth. I'm happy to open a PR that implements the same pattern that I used in gaplaylength.js.

What do you think?

**Comment by robflaherty** [comment]
I'm definitely open to it! It was on the roadmap at one point in the past but I decided to prioritize other things. If you want to work on it and send a PR that would be awesome.

**Comment by leighmcculloch** [comment]
Excellent. When I did gaplaylength as non-jQuery I started using webpack to compile, it makes it easy to import one lib into another and use it, and you get a UMD library out of it which will work with requirejs, commonjs, or just by itself. Are you open to me doing that as well? If so I'll open a few PRs that will get us to webpack, and then split it up:

1. Add NPM
2. Add webpack
2. Break out the core lib and make a jQuery wrapper

Let me know if you're up for this approach.

**Comment by robflaherty** [comment]
Hey,
I'm not familiar with webpack. Since it's a simple plugin I like to keep the dependencies as limited and as simple as possible. So I'd prefer to keep it as is. But let me know if you think this is a mistake.

If the non-jQuery version works well I would want to retire the jQuery version. Not sure there's a benefit in offering both...

Thanks

**Comment by leighmcculloch** [comment]
The only benefit to offering both is to make it more familiar for jQuery users who aren't familiar with working without it.

I'll do it without webpack.

**Comment by leighmcculloch** [comment]
I'd like to do this supporting IE9+ only, but then providing a list of optional shims in the README that will allow support in older versions of IE. Do you have an opinion on this?

**Comment by leighmcculloch** [comment]
Actually, scratch that idea. I don't think it will be hard to support all the way back to IE6. :soon:

**Comment by robflaherty** [comment]
:) Would like to keep IE8 support for now but happy to drop IE7.

**Comment by leighmcculloch** [comment]
Just putting this reference here: https://github.com/robflaherty/jquery-scrolldepth/pull/74
