### ISSUE TITLE
No events firing

### ISSUE THREAD

**Issue by timpwbaker** [robflaherty/jquery-scrolldepth#75]
I've got no events firing. As far as I can see I've got it all installed and in the correct order, and I've tried switching off things that I've seen mentioned as possible causes of conflict. Any ideas?

It's a drupal site, so lots of stuff in there that could be causing the issue.

URL: https://www.breastcancercare.org.uk/

Really excited to get it working though. Looks great.

**Comment by ewlarson** [comment]
Looks like you're using an older release via that CDN.  Before debugging anymore, try updating to the latest release (0.8.0) and see what happens: https://github.com/robflaherty/jquery-scrolldepth/releases/tag/0.8.0

**Comment by robflaherty** [comment]
Hey - There's a JS error on the page. I'd try resolving that first.
![screen shot 2015-08-12 at 1 24 01 pm](https://cloud.githubusercontent.com/assets/159644/9231293/7755dbb2-40f5-11e5-861b-6d3d13e01f90.png)

**Comment by robflaherty** [comment]
Oh, this is a google tag manger config problem. The events are firing correctly into the dataLayer.

![screen shot 2015-08-12 at 1 26 35 pm](https://cloud.githubusercontent.com/assets/159644/9231347/caa48264-40f5-11e5-92b1-7a1d2726f705.png)
