### ISSUE TITLE
Non-GA version

### ISSUE THREAD

**Issue by migig** [robflaherty/jquery-scrolldepth#79]
This library is really useful, and does stuff that other waypoint libraries don't do out of the box.

So would be useful to have a version/fork of this which doesn't include the analytics stuff, only the waypoint and scroll depth checking.

So instead of automatic submission to GA, I'd get an event with the data, and I'd do with it what I like.

EDIT: I see I can supply my own callback function. But the library still is "GA heavy". Would be nice to have a smaller stripped-down version alongside the .js and .min.js. Just a thought. Or else rename this to "jquery-scrolldepth-ga".... :grinning: :smiling_imp:

**Comment by migig** [comment]
No thoughts :disappointed:

**Comment by robflaherty** [comment]
sorry :)

The plugin is "GA heavy" by design—it was originally a GA plugin and that's still the primary use case for it. Also, it's a tiny plugin, about 1K gzipped. I don't see a benefit to stripping out the GA code to make it smaller.

**Comment by migig** [comment]
Okay that was a good reply... Plugins are usually based on what suits the original author. If I wrote a plugin it wouldn't have the GA stuff in there by default, but as an addin! So I guess I'm asking for too much! :laughing: 

Your plugins are awesome BTW.

**Comment by robflaherty** [comment]
Thanks, glad you like the plugins :)

If I were writing the plugin now I would probably make it non-GA dependent but when I wrote it 3 years ago the goal was to have it integrate with GA as easily as possible.
