### ISSUE TITLE
No baseline event

### ISSUE THREAD

**Issue by justinae** [robflaherty/jquery-scrolldepth#80]
Plugin installed and working. I see in your change log that you removed the baseline event. I don't see in documentation anywhere about tracking if a user sees the page and leaves without any scrolling.

Side question. Is it possible to break into 20%?

Much appreciated.

**Comment by leeclemmer** [comment]
I also just noticed that the Baseline event was removed, but couldn't find the rationale behind removing it.   What's the thinking there? Is it that pageviews sets the floor?

**Comment by robflaherty** [comment]
Yeah, basically the pageview event sets the floor. A number of people had asked for an option to turn the event off and the more I looked at it the more I questioned the value of having it at all. Alternatives:

If you want to see traffic that didn't scroll to at least 25% you could create a segment that shows sessions without a Scroll Depth event.

Or you could add JS to your site to send your own baseline event. It's just an event that fires immediately on page load.

**Comment by leeclemmer** [comment]
Cool, makes sense, thanks for the info.
