### ISSUE TITLE
Wordpress issue with scrolldepth

### ISSUE THREAD

**Issue by andreiiBC** [robflaherty/jquery-scrolldepth#82]
Hello,

I have a Wordpress version 3.9 site. I have tried to install scrolldepth for our google analytics but it doesn't work. I did everything that was specified in the guide. We have jquerry 1.11 and I have implemented the code right after the analytics one. First we believed that the problem is our analytics code which was in the footer. But after I've moved it on the header (with the scrolldepth code beneath it), it still didn't sent any events to our analytics.
Help is appreciated :)
Thanks!

**Comment by robflaherty** [comment]
If you can send the URL to hello@parsnip.io I can take a quick look
