### ISSUE TITLE
Data in analytics

### ISSUE THREAD

**Issue by clarkk** [robflaherty/jquery-scrolldepth#84]
Have now added this plugin on my page

```
			$(function(){
				$.scrollDepth({
					minHeight : 2000,
					userTiming : false
				});
			});
```

But where can you find the recorded data in Google analytics?!

**Comment by robflaherty** [comment]
Where to find the data is explained on the [project page](http://scrolldepth.parsnip.io/). More detailed info is in [this post](https://medium.com/google-analytics/hacking-google-analytics-24762924fbf8#.mhu0ryvtq).

**Comment by clarkk** [comment]
I think you should add the second link somewhere.. I think others than me look for the same question

**Comment by robflaherty** [comment]
It's linked on the project page
