### ISSUE TITLE
[question] Support for Google Analytics Debugger?

### ISSUE THREAD

**Issue by petrklus** [robflaherty/jquery-scrolldepth#90]
Hello!

I was wondering, is [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) supported? I am not seeing any scroll-based feedback in the console. I can see output from the following snippet:

```js
jQuery.scrollDepth({
  eventHandler: function(data) {
    console.log(data)
  }
});
```
But no output from GA debugger when running parameter-less.

**Comment by robflaherty** [comment]
Hi,
Using the eventHandler option turns off the GA events, so you won't see anything in the GA debugger. Change to this and should see the GA events firing:

`jQuery.scrollDepth();`

**Comment by petrklus** [comment]
Yes, I understand that - but I am not seeing any events fire when using the standard example. The only time I can see anything happening is when I use the console.log

**Comment by petrklus** [comment]
@robflaherty - is the analytics debugger supported?

**Comment by robflaherty** [comment]
Yes. You can see what it looks like by running the GA debugger on another site using scroll depth. For example: https://teamtreehouse.com/

**Comment by petrklus** [comment]
Hmm I do not see any of that - see [here](http://enterprise.ft.com/en-gb/) for an example - the console.log method works (meaning the plugin itself works) but when I switch to GA mode, it does not seem to be working.

**Comment by robflaherty** [comment]
Thanks for the URL. So you're using GTM? The Scroll Depth events are firing into the dataLayer correctly so seems like the problem is on the GTM config side of things.

Note that if the plugin detects the `dataLayer` variable it will assume you're using GTM and will push the events into the dataLayer instead of firing GA events.

![screen shot 2016-05-17 at 5 19 14 pm](https://cloud.githubusercontent.com/assets/159644/15339686/a10d3aba-1c53-11e6-9f76-ee0b60813ba1.png)

**Comment by petrklus** [comment]
Yes, that is correct - we are using GTM, however, as odd as it may seem, not for GA - which is standalone. 

Is there any way to force the plugin to use the GA directly rather than using GTM?

**Comment by robflaherty** [comment]
Yep, there's a gtm override for exactly that case :) gtmOverride: true.

See docs on project page.

**Comment by petrklus** [comment]
Thank you! Missed that setting.
