### ISSUE TITLE
Ignore footer

### ISSUE THREAD

**Issue by robinzimmermann** [robflaherty/jquery-scrolldepth#91]
I would like the percentage tracking to ignore the footer. That is, I want the 100% event to fire at the _top_ of the footer, where the content ends.

This is because the footer is quite large and can be a significant size compared to the rest of the page. If someone reads the content of the page and then stops, they've actually seen 100% of the content, but the last event reported is 75%.

**Comment by robflaherty** [comment]
Hi,
I'm planning to add an option that will let you scope the plugin to a container div and that would solve your use case. In the meantime you could use the element tracking option to fire an event when someone reaches the footer.
