### ISSUE TITLE
How to fire events on segment instead of GA?

### ISSUE THREAD

**Issue by jinxac** [robflaherty/jquery-scrolldepth#97]
We use segment for analytics under which we have added integrations for GA,mixpanel etc.. So I was wondering how I do I fire event calls to segment so that it is send to all integrations automatically.

Thanks in advance.

**Comment by gkogan** [comment]
@jinxac I made a modified version that works with Segment. See this gist: https://gist.github.com/gkogan/d3427d27e60a93fb3a66bbf078564270

**Comment by jinxac** [comment]
sure let me check it out once today.. thanks :)

**Comment by gkogan** [comment]
@jinxac actually I made forked this into a Segment-specific scroll tracker: https://github.com/gkogan/segment-scrolldepth

Hope that helps.

**Comment by robflaherty** [comment]
The `eventHandler` option allows for integration with other analytics services. Note that the `eventHandler` callback overrides (turns off) the built in GA events.
