### ISSUE TITLE
Possible to have add eventHandler along with default GA tracking? 

### ISSUE THREAD

**Issue by vicngtor** [robflaherty/jquery-scrolldepth#98]
Looking to add mixpanel tracking along with GA tracking. 

Is this possible?

**Comment by robflaherty** [comment]
Yes, using the eventHandler option but you'll need to add your own GA event code to the callback. Like this:

```
jQuery.scrollDepth({
  eventHandler: function(data) {
    // Mixpanel event goes here
    // GA event goes here
  }
});
```
